Add support to humanizing a TimeOnly as a readable clock notation
Humanizr/Humanizer pull request #1134
Opened 2021-10-27 04:10 UTC by strobelt

Add support to humanizing a TimeOnly as a readable clock notation string as asked on #1081 
Uses the Converter architecture based on the DateOnly ToOrdinal converter and extension

2021-10-27 08:05 UTC, hangy commented on src/Humanizer.Tests/ApiApprover/PublicApiApprovalTest.Approve_Public_Api.approved.txt.orig
> +﻿[assembly: System.Resources.NeutralResourcesLanguageAttribute("en")]
Did you add this file by accident?

2021-10-27 08:09 UTC, hangy commented on src/Humanizer/Localisation/TimeToClockNotation/PtBrTimeOnlyToClockNotationConverter.cs
> +    public class PtBrTimeOnlyToClockNotationConverter : ITimeOnlyToClockNotationConverter
Just to stick to the existing naming in this project (eg. `BrazilianPortugueseNumberToWordsConverter`), I'd name this  `BrazilianPortugueseTimeOnlyToClockNotationConverter`.

2021-10-27 08:16 UTC, hangy commented on src/Humanizer.Tests.Shared/Localisation/en/TimeToClockNotationTests.cs
> +        [UseCulture("pt-BR")]
This test should probably be in it's own class in the `Humanizer.Tests.Localisation.ptBR` namespace.

2021-10-27 08:23 UTC, hangy commented on src/Humanizer/Localisation/TimeToClockNotation/DefaultTimeOnlyToClockNotationConverter.cs
> +                { Minute: 00 } => $"{normalizedHour.ToWords()} o'clock",
I wonder if it would be better to move these strings to resources. For any other language than English, this produces a mix of English and the other language. For example, you register `DefaultTimeOnlyToClockNotationConverter` for the `de` locale, which outputs "vier o'clock", while "vier Uhr" would be correct. Generally, that should make adding support for other languages easier.

2021-10-27 14:43 UTC, strobelt commented on src/Humanizer/Localisation/TimeToClockNotation/PtBrTimeOnlyToClockNotationConverter.cs
> +    public class PtBrTimeOnlyToClockNotationConverter : ITimeOnlyToClockNotationConverter
Thanks! Fixed it!

2021-10-27 14:43 UTC, strobelt commented on src/Humanizer.Tests.Shared/Localisation/en/TimeToClockNotationTests.cs
> +        [UseCulture("pt-BR")]
Moved it to the right folder!

2021-10-27 14:44 UTC, strobelt commented on src/Humanizer.Tests/ApiApprover/PublicApiApprovalTest.Approve_Public_Api.approved.txt.orig
> +﻿[assembly: System.Resources.NeutralResourcesLanguageAttribute("en")]
Yes I did. Sorry! 
It was late in the night and I accidentally added the .orig files KDiff creates. 
Thanks for catching this!

2021-10-27 15:19 UTC, strobelt commented on src/Humanizer/Localisation/TimeToClockNotation/DefaultTimeOnlyToClockNotationConverter.cs
> +                { Minute: 00 } => $"{normalizedHour.ToWords()} o'clock",
I really thought about it while I was implementing it. It would be really good for most languages I know, but I think some languages will have different ways to "read the time". For example, in US english we just tell as "hours minutes", while in portuguese we tell it as "hours **and** minutes". And from what I saw other languages have different ordering on the special cases, like in french we tell 03:45 as "quatre moins le quart" instead of "a quarter to four" in english.

Because of these specificities I went with strings inside the converters instead. Do you have any idea how we could use resources in this case?

2021-10-27 17:18 UTC, hangy commented on src/Humanizer/Localisation/TimeToClockNotation/DefaultTimeOnlyToClockNotationConverter.cs
> +                { Minute: 00 } => $"{normalizedHour.ToWords()} o'clock",
ACK that's a good point. I'm not sure if moving the strings to resources would suffice for all cases. Maybe it would be easiest just remove the registration for "de" for now, because that's not correct (and will use the default anyways)?

2021-10-27 17:18 UTC, hangy commented on src/Humanizer.Tests/ApiApprover/PublicApiApprovalTest.Approve_Public_Api.approved.txt.orig
> +﻿[assembly: System.Resources.NeutralResourcesLanguageAttribute("en")]
I know that feeling. 😄

2021-10-27 19:59 UTC, hangy commented on src/Humanizer.Tests/ApiApprover/PublicApiApprovalTest.approve_public_api.approved.txt
> +    }
These classes shouldn't be part of the public API. I think in the other cases (ie. `Ordinalizers`), they have `internal` visibility.

2021-10-28 11:54 UTC, clairernovotny commented on src/Humanizer/Configuration/TimeOnlyToClockNotationConvertersRegistry.cs
> +            Register("en-UK", new DefaultTimeOnlyToClockNotationConverter());
Does this need to be `en-US` and `en-UK`? Can it just be `en`? Is it needed at all given that it's the default?

2021-10-30 22:08 UTC, strobelt commented
Great! I made the change and went with the enum to make it more clear when using the converter.
What do you think?

2021-11-04 14:23 UTC, clairernovotny requested changes

2021-11-04 14:23 UTC, clairernovotny commented on src/Humanizer.Tests/ApiApprover/PublicApiApprovalTest.approve_public_api.approved.txt
> +    public enum ClockNotationRounding
This enum should be in the root `Humanizer` namespace so that people don't need a deep include for this

2021-11-11 15:05 UTC, clairernovotny commented
Ping @strobelt? I'd love to get a new release out that includes these changes!

2021-11-11 15:11 UTC, strobelt commented
Hi @clairernovotny! I just updated the PR. Thanks for the heads-up with this

2021-11-11 18:34 UTC, clairernovotny approved these changes

2021-11-11 18:35 UTC, merged