Add tamil translations
Humanizr/Humanizer pull request #979
Opened 2020-09-20 03:58 UTC by mohamedmahir

Here is a checklist you should tick through before submitting a pull request: 
 - [ X] Implementation is clean
 - [X ] Code adheres to the existing coding standards; e.g. no curlies for one-line blocks, no redundant empty lines between methods or code blocks, spaces rather than tabs, etc.
 - [ ] No ReSharper warnings
 - [ X] There is proper unit test coverage
 - [ ] If the code is copied from StackOverflow (or a blog or OSS) full disclosure is included. That includes required license files and/or file headers explaining where the code came from with proper attribution
 - [X ] There are very few or no comments (because comments shouldn't be needed if you write clean code)
 - [ ] Xml documentation is added/updated for the addition/change
 - [ ] Your PR is (re)based on top of the latest commits from the `dev` branch (more info below)
 - [ ] Link to the issue(s) you're fixing from your PR description. Use `fixes #<the issue number>`
 - [ ] Readme is updated if you change an existing feature or add a new one
 - [ X] Run either `build.cmd` or `build.ps1` and ensure there are no test failures

2020-09-20 05:29 UTC, mohamedmahir commented
Can someone help me on why build is failing?

2020-09-30 22:28 UTC, clairernovotny requested changes
Thank you for this translation. We can merge this after the two small items are addressed. We let the commit history serve as credit.

2020-09-30 22:28 UTC, clairernovotny commented on src/Humanizer/Localisation/NumberToWords/TamilNumberToWordsConverter.cs
> +//Author:Mohamed Mahir - mahir78@gmail.com
Pease remove this line

2020-09-30 22:28 UTC, clairernovotny commented on NuSpecs/Humanizer.Core.ta.nuspec
> +    <authors>Mehdi Khalili, Claire Novotny, Mohamed Mahir</authors>
```suggestion
    <authors>Mehdi Khalili, Claire Novotny</authors>
```
Please change this

2020-09-30 22:29 UTC, clairernovotny commented on src/Humanizer/Localisation/NumberToWords/TamilNumberToWordsConverter.cs
> +//Author:Mohamed Mahir - mahir78@gmail.com
```suggestion
```

2020-09-30 22:30 UTC, merged