Implement ja-JP for Number to Word
Humanizr/Humanizer pull request #981
Opened 2020-09-24 03:58 UTC by Hee-San

Here is a checklist you should tick through before submitting a pull request: 
 - [x] Implementation is clean
 - [x] Code adheres to the existing coding standards; e.g. no curlies for one-line blocks, no redundant empty lines between methods or code blocks, spaces rather than tabs, etc.
 - [ ] No ReSharper warnings — no can do, I'm on macOS
 - [x] There is proper unit test coverage
 - [x] If the code is copied from StackOverflow (or a blog or OSS) full disclosure is included. That includes required license files and/or file headers explaining where the code came from with proper attribution
 - [x] There are very few or no comments (because comments shouldn't be needed if you write clean code)
 - [ ] Xml documentation is added/updated for the addition/change — not really
 - [ ] Your PR is (re)based on top of the latest commits from the `dev` branch (more info below) — there's no dev branch in origin.
 - [x] Link to the issue(s) you're fixing from your PR description. Use `fixes #<the issue number>`
 - [ ] Readme is updated if you change an existing feature or add a new one — not applicable
 - [ ] Run either `build.cmd` or `build.ps1` and ensure there are no test failures — no can do, I'm on macOS

fixes #980

2020-09-24 03:58 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/Humanizr/Humanizer?pullRequest=981) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/Humanizr/Humanizer?pullRequest=981) before we can accept your contribution.<br/><br/>:x: Hee-San [sign now](https://cla.dotnetfoundation.org/Humanizr/Humanizer?pullRequest=981)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/Humanizr/Humanizer?pullRequest=981) it.</sub>

2020-09-26 14:38 UTC, clairernovotny requested changes
Looks good with the two changes

2020-09-26 14:38 UTC, clairernovotny commented on src/Humanizer.Tests.Shared/Humanizer.Tests.Shared.shproj
> +    <Service Include="$(MSBuildThisFileDirectory){82a7f48d-3b50-4b1e-b82e-3ada8210c358}" />
Please remove this line

2020-09-26 14:38 UTC, clairernovotny commented on src/Humanizer.Tests.Shared/Humanizer.Tests.Shared.projitems
> +    <Compile Include="$(MSBuildThisFileDirectory)Localisation\ja\NumberToWordsTests.cs" Condition=" '$(EnableDefaultCompileItems)' == 'true' " />
```suggestion
    <Compile Include="$(MSBuildThisFileDirectory)Localisation\ja\NumberToWordsTests.cs"  />
```

2020-09-29 09:17 UTC, Hee-San commented on src/Humanizer.Tests.Shared/Humanizer.Tests.Shared.shproj
> +    <Service Include="$(MSBuildThisFileDirectory){82a7f48d-3b50-4b1e-b82e-3ada8210c358}" />
Fixed at c207cb0.

2020-09-29 09:17 UTC, Hee-San commented on src/Humanizer.Tests.Shared/Humanizer.Tests.Shared.projitems
> +    <Compile Include="$(MSBuildThisFileDirectory)Localisation\ja\NumberToWordsTests.cs" Condition=" '$(EnableDefaultCompileItems)' == 'true' " />
Fixed at c207cb0.

2020-09-30 22:23 UTC, merged

2020-09-30 22:23 UTC, clairernovotny commented
Thanks!